import java.util.HashMap;

/**
* OOPSBannerApp UC8 – Banner Display Application
*
* This class demonstrates the creation of a visual banner displaying the word "OOPS"
* using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
* console using individual print statements for each line, creating a decorative
* text effect.
*
* The banner is generated by printing predefined string patterns line by line,
* where each line contributes to forming the letters O, O, P, and S in a stylized format.
* This extends a basic user story by adding visual presentation to a simple message output.
* This program uses HashMap to store the Characters to their corresponding string pattern in an array. Then Static methods are
* defined generate this map and to print the character provided in the message in the main function
* @author Developer
* @version 8
*/
public class OOPS{
 
	public static HashMap<Character, String[]> createCharacterMap()
	{
		HashMap<Character, String[]> charMap=new HashMap<>();
		charMap.put('O',new String[]{
						"     ***   ",
						"   **   ** ",
						"  **     **",
						"  **     **",
						"  **     **",
						"  **     **",
						"  **     **",
						"   **   ** ",
						"     ***   "});
		charMap.put('P',new String[]{
						"*******",
						"**    *",
						"**    *",
						"**    *",
						"*******",
						"**     ",
						"**     ",
						"**     ",
						"**     "});
		charMap.put('S',new String[]{
						"   ***** ",
						" **      ",
						"**       ",
						" **      ",
						"   ***   ",
						"      ** ",
						"       **",
						"      ** ",
						" *****   "});
		return charMap;
	}
	public static void displayBanner(String message, HashMap<Character,String[]> charMap)
	{
		int height = charMap.get(message.charAt(0)).length;

			for (int i = 0; i < height; i++) {   
				for (char c : message.toCharArray()) {  
					System.out.print(charMap.get(c)[i] + " "); 
				}
				System.out.println(); 
			}

	}
	public static void main(String[] args){
		HashMap<Character, String[]> charMap=createCharacterMap();
		String message = "OOPS";
		displayBanner(message, charMap);
 
	}

 
}